// Third-party notices: the build writes dist/THIRD-PARTY-NOTICES.txt, the page
// links to it, and it covers every crate whose code is actually inside the
// shipped .wasm (read from the module's name section).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { dist, root } from './helpers.mjs';

const file = join(dist, 'THIRD-PARTY-NOTICES.txt');
const read = () => readFileSync(file, 'utf8');

/** Crate names in the wasm "name" custom section, e.g. `core[ed71…]::fmt::write`. */
function crateNamesInWasm(bytes) {
  const [sec] = WebAssembly.Module.customSections(new WebAssembly.Module(bytes), 'name');
  if (!sec) return null;
  const b = new Uint8Array(sec);
  let p = 0;
  const leb = () => {
    let r = 0;
    for (let s = 0; ; s += 7) {
      const x = b[p++];
      r += (x & 0x7f) * 2 ** s;
      if (!(x & 0x80)) return r;
    }
  };
  const names = new Set();
  while (p < b.length) {
    const id = b[p++];
    const end = leb() + p;
    if (id === 1) {
      // function names: count, then (index, length, UTF-8 name) pairs
      for (let n = leb(); n > 0; n--) {
        leb();
        const len = leb();
        const fn = new TextDecoder().decode(b.subarray(p, p + len));
        p += len;
        for (const m of fn.matchAll(/([A-Za-z_][A-Za-z0-9_]*)\[[0-9a-f]{16}\]/g)) names.add(m[1]);
      }
    }
    p = end;
  }
  return names;
}

test('dist/ ships THIRD-PARTY-NOTICES.txt', () => {
  assert.ok(existsSync(file), 'dist/THIRD-PARTY-NOTICES.txt is missing (run npm run build)');
  assert.ok(read().length > 1000);
});

test('the colophon links to the notices', () => {
  const html = readFileSync(join(dist, 'index.html'), 'utf8');
  assert.match(html, /<footer class="colophon">[\s\S]*href="THIRD-PARTY-NOTICES\.txt"[\s\S]*<\/footer>/);
});

test('the notices name the exact wasm-bindgen version and carry the licence texts', () => {
  const text = read();
  const lock = readFileSync(join(root, 'Cargo.lock'), 'utf8');
  const version = /name = "wasm-bindgen"\nversion = "([^"]+)"/.exec(lock)[1];
  assert.match(text, new RegExp(`^wasm-bindgen ${version.replace(/\./g, '\\.')}$`, 'm'));
  assert.match(text, /pkg\/overprint\.js is generated by wasm-bindgen-cli/);
  assert.match(text, /^Rust standard library \(core, alloc, std\) \d+\.\d+\.\d+$/m);
  assert.match(text, /^dlmalloc \d+\.\d+\.\d+$/m);
  assert.match(text, /Permission is hereby granted, free of charge/);
  assert.match(text, /UNICODE LICENSE V3/);
  assert.match(text, /Google Fonts[\s\S]*SIL Open Font License 1\.1/);
  assert.doesNotMatch(text, /\/Users\/|\/home\//, 'no local paths');
});

test('every crate compiled into the .wasm has a notice', (t) => {
  const names = crateNamesInWasm(readFileSync(join(dist, 'pkg', 'overprint_bg.wasm')));
  if (!names) return t.skip('the .wasm has no name section (stripped), so there is nothing to cross-check');
  const text = read();
  const own = new Set(['overprint', '__rustc']); // our code, and rustc's allocator shims
  const std = new Set(['core', 'alloc', 'std']);
  assert.ok(names.has('wasm_bindgen'), `expected wasm_bindgen among ${[...names]}`);
  for (const name of names) {
    if (own.has(name)) continue;
    if (std.has(name)) {
      assert.match(text, /^Rust standard library \(core, alloc, std\) /m);
      continue;
    }
    const heading = new RegExp(`^${name.replace(/_/g, '[-_]')} \\d+\\.\\d+\\.\\d+`, 'm');
    assert.match(text, heading, `${name} is in the .wasm but has no notice`);
  }
});
