// Writes dist/THIRD-PARTY-NOTICES.txt: every piece of third-party code that
// ships in dist/, with its version, copyright, licence text and source.
//
// What ships (checked against the .wasm name section, see
// tests/notices.test.mjs):
//   - Rust crates compiled for wasm32-unknown-unknown (from `cargo metadata`,
//     normal dependencies only: proc-macros and build scripts run on the build
//     machine and ship nothing). Licence texts are read from each crate's own
//     source in the Cargo registry.
//   - The Rust standard library (core, alloc, std) and the allocator it uses on
//     wasm32 (dlmalloc). Texts are read from the Rust toolchain's own
//     share/doc/rust files.
//   - The JavaScript glue in pkg/overprint.js, generated by wasm-bindgen-cli.
import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const TARGET = 'wasm32-unknown-unknown';
const RULE = '-'.repeat(78);
const NEXT = '\n' + ' '.repeat(13); // continuation line under a '  Label:    ' field

function fail(msg) {
  throw new Error(`third-party notices: ${msg}`);
}

function entities(s) {
  return s
    .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCodePoint(parseInt(n, 16)))
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, '&');
}
const noEmail = (s) => s.replace(/\s*<[^>]*@[^>]*>/g, '').trim();
const tidy = (text) => text.replace(/\r\n/g, '\n').replace(/^\n+|\s+$/g, '');

/** Crates Cargo compiles for the wasm target, and those that only run at build time. */
export function crates(root) {
  const meta = JSON.parse(
    execFileSync('cargo', ['metadata', '--format-version', '1', '--filter-platform', TARGET, '--locked'], {
      cwd: root,
      encoding: 'utf8',
      maxBuffer: 64 << 20,
    }),
  );
  const pkgs = new Map(meta.packages.map((p) => [p.id, p]));
  const nodes = new Map(meta.resolve.nodes.map((n) => [n.id, n]));
  const isProcMacro = (p) => p.targets.some((t) => t.kind.includes('proc-macro'));
  const shipped = new Set();
  const stack = [meta.resolve.root];
  while (stack.length) {
    const id = stack.pop();
    for (const dep of nodes.get(id).deps) {
      if (!dep.dep_kinds.some((k) => k.kind === null)) continue; // dev or build only
      if (isProcMacro(pkgs.get(dep.pkg)) || shipped.has(dep.pkg)) continue;
      shipped.add(dep.pkg);
      stack.push(dep.pkg);
    }
  }
  const byName = (a, b) => a.name.localeCompare(b.name);
  const rootPkg = pkgs.get(meta.resolve.root);
  return {
    shipped: [...shipped].map((id) => pkgs.get(id)).sort(byName),
    buildOnly: meta.packages.filter((p) => p.id !== rootPkg.id && !shipped.has(p.id)).sort(byName),
  };
}

function crateEntry(p) {
  const dir = dirname(p.manifest_path);
  const files = readdirSync(dir).filter((f) => /^(licen[cs]e|copying|copyright|notice)/i.test(f)).sort();
  // Dual-licensed "MIT OR Apache-2.0" crates are used under the MIT option, so
  // the MIT text is the one that applies. Any other licence file (for example
  // unicode-ident's Unicode-3.0 data licence) applies as well and is included.
  const dualMit = /\bMIT OR Apache-2\.0\b|\bApache-2\.0 OR MIT\b|MIT\/Apache-2\.0/.test(p.license ?? '');
  const texts = files.filter((f) => !(dualMit && /apache/i.test(f)));
  if (!texts.length) fail(`no licence file found for ${p.name} ${p.version}`);
  const bodies = texts.map((f) => [f, tidy(readFileSync(join(dir, f), 'utf8'))]);
  // Copyright lines from each licence file; a file without one (common for
  // MIT texts) is credited to the crate's authors as listed in Cargo.toml.
  const authors = `the ${p.name} authors (${p.authors.map(noEmail).join(', ')})`;
  const copyright = [
    ...new Set(
      bodies.flatMap(([, t]) => {
        const found = t
          .split('\n')
          .filter((l) => /^\s*copyright\b.*(\(c\)|©|\d{4})/i.test(l))
          .map((l) => l.trim().replace(/^copyright\s+/i, ''));
        return found.length ? found : [authors];
      }),
    ),
  ];
  return {
    name: p.name,
    version: p.version,
    what: '',
    copyright: copyright.join(NEXT),
    licence: p.license + (dualMit ? ' (MIT chosen where there is a choice)' : ''),
    source: `https://crates.io/crates/${p.name}/${p.version}` + (p.repository ? `${NEXT}${p.repository}` : ''),
    texts: bodies,
  };
}

/** The Rust standard library and its wasm32 allocator, from the toolchain's own notices. */
function rustEntries() {
  const vv = execFileSync('rustc', ['-vV'], { encoding: 'utf8' });
  const release = /^release: (\S+)/m.exec(vv)?.[1] ?? fail('cannot read rustc release');
  const commit = /^commit-hash: (\S+)/m.exec(vv)?.[1] ?? fail('cannot read rustc commit');
  const sysroot = execFileSync('rustc', ['--print', 'sysroot'], { encoding: 'utf8' }).trim();
  const doc = join(sysroot, 'share', 'doc', 'rust');
  const htmlPath = join(doc, 'COPYRIGHT-library.html');
  if (!existsSync(htmlPath)) fail('the Rust toolchain has no share/doc/rust/COPYRIGHT-library.html');
  const html = readFileSync(htmlPath, 'utf8');

  const inTree = (path) => {
    const at = html.indexOf(`<code>${path}</code>`);
    if (at < 0) fail(`COPYRIGHT-library.html has no entry for ${path}`);
    const seg = html.slice(at, at + 2000);
    return {
      licence: entities(/<b>License:<\/b>\s*([^<]+)<\/p>/.exec(seg)[1].trim()),
      copyright: entities(/<b>Copyright:<\/b>\s*([^<]+)<\/p>/.exec(seg)[1].trim()),
    };
  };
  const std = inTree('.');
  if (!/\bMIT\b/.test(std.licence)) fail(`unexpected standard library licence: ${std.licence}`);
  const unicode = inTree('library/core/src/unicode');

  const mitTemplate = tidy(readFileSync(join(doc, 'licenses', 'MIT.txt'), 'utf8'));
  const mit = mitTemplate.replace(/^Copyright \(c\) <year> <copyright holders>$/m, `Copyright (c) ${std.copyright}`);
  const unicodeText = tidy(readFileSync(join(doc, 'licenses', 'Unicode-3.0.txt'), 'utf8'));

  const out = [
    {
      name: 'Rust standard library (core, alloc, std)',
      version: release,
      what: 'compiled into pkg/overprint_bg.wasm',
      copyright: `${std.copyright}${NEXT}Unicode data tables in core: Copyright ${unicode.copyright}`,
      licence: `${std.licence} (MIT chosen where there is a choice); core's Unicode tables: ${unicode.licence}`,
      source: `https://github.com/rust-lang/rust/tree/${commit}/library`,
      texts: [
        ['MIT (share/doc/rust/licenses/MIT.txt)', mit],
        [`${unicode.licence} (share/doc/rust/licenses/Unicode-3.0.txt)`, unicodeText],
      ],
    },
  ];

  // std's allocator on wasm32-unknown-unknown.
  const h3 = /<h3>📦 dlmalloc-([\d.]+)<\/h3>/.exec(html) ?? fail('COPYRIGHT-library.html has no dlmalloc entry');
  const seg = html.slice(h3.index, html.indexOf('<h3>', h3.index + 5));
  const licence = entities(/<b>License:<\/b>\s*([^<]+)<\/p>/.exec(seg)[1].trim());
  const mitText = /<code>LICENSE-MIT<\/code><\/summary>\s*<pre>([\s\S]*?)<\/pre>/.exec(seg)?.[1];
  if (!mitText) fail('no LICENSE-MIT text for dlmalloc');
  const dlText = tidy(entities(mitText));
  out.push({
    name: 'dlmalloc',
    version: h3[1],
    what: "the Rust standard library's memory allocator on wasm32, compiled into pkg/overprint_bg.wasm",
    copyright: dlText.split('\n').find((l) => /^copyright/i.test(l))?.replace(/^copyright\s+/i, '') ?? 'the dlmalloc authors',
    licence: `${licence} (MIT chosen where there is a choice)`,
    source: `https://crates.io/crates/dlmalloc/${h3[1]}`,
    texts: [['LICENSE-MIT', dlText]],
  });
  return out;
}

export function notices(root) {
  const lock = readFileSync(join(root, 'Cargo.lock'), 'utf8');
  const bindgen = /name = "wasm-bindgen"\nversion = "([^"]+)"/.exec(lock)?.[1] ?? fail('wasm-bindgen not in Cargo.lock');
  const { shipped, buildOnly } = crates(root);
  const entries = shipped.map(crateEntry);
  for (const e of entries) {
    e.what =
      e.name === 'wasm-bindgen'
        ? `compiled into pkg/overprint_bg.wasm; the JavaScript glue in pkg/overprint.js is generated by wasm-bindgen-cli ${bindgen} (same project, same licence)`
        : 'compiled for wasm32 as a dependency of wasm-bindgen (the linker drops any code this build does not use)';
  }
  entries.unshift(...rustEntries());

  const lines = [
    'THIRD-PARTY NOTICES for overprint',
    '',
    'overprint itself is MIT licensed (Copyright (c) 2026 ramenprotokol).',
    'This file lists the third-party code that ships in this site, with each',
    "component's version, copyright, licence and source. It is written by",
    '`npm run build` from the licence files of the exact versions that were',
    'compiled.',
    '',
    'Components:',
    ...entries.map((e) => `  - ${e.name} ${e.version}`),
    '',
    'Build-time only (proc-macros and build scripts that run on the build',
    'machine; none of their code ships):',
    `  ${buildOnly.map((p) => `${p.name} ${p.version}`).join(', ')}`,
    '',
    'Not shipped in this site: the Archivo and IBM Plex Mono typefaces are',
    'loaded from Google Fonts (fonts.googleapis.com) when the page opens. Both',
    'are licensed under the SIL Open Font License 1.1.',
    '',
  ];
  for (const e of entries) {
    lines.push(
      RULE,
      `${e.name} ${e.version}`,
      `  Ships:     ${e.what}`,
      `  Copyright: ${e.copyright}`,
      `  Licence:   ${e.licence}`,
      `  Source:    ${e.source}`,
      '',
    );
    for (const [label, text] of e.texts) lines.push(`  --- ${label} ---`, '', text, '');
  }
  lines.push(RULE, '');
  return lines.join('\n');
}

export function writeNotices(root, dist) {
  const text = notices(root);
  if (/\/Users\/|\/home\//.test(text)) fail('a local path leaked into the notices');
  writeFileSync(join(dist, 'THIRD-PARTY-NOTICES.txt'), text);
  return text;
}
